### ISSUE TITLE
키보드 마우스 조작

### ISSUE THREAD

**Issue by sindydwns** [CubeRT7/minirt#43]
- [x] P: (Position)
  - [x] x: 카메라 좌표계 x 축 이동
  - [x] y: 카메라 좌표계 y 축 이동 
  - [x] z: 카메라 좌표계 z 축 이동
- [x] R: (Rotate)
  - [x] x: 카메라 좌표계 x 축 회전
  - [x] y: 카메라 좌표계 y 축 회전
  - [x] z: 카메라 좌표계 z 축 회전
- [x] S: (Scale)
  - [x] r: 로컬 좌표계 radius 조정
  - [x] h: 로컬 좌표계 height 조정

**Comment by iijung** [comment]
- cac3b0321fadc1add3f6e3ded7b31feabe57da59
